### ISSUE TITLE
Todo: change require statements to error messages

### ISSUE THREAD

**Issue by TobiasBK** [Alcibiades-Capital/valorem-options-contracts#29]
Hi,
I came across this repo when I was looking for testing examples for an options contract I wrote. I really like the design. 
I can pick up some todos for you, if you guys need.

**Comment by 0xAlcibiades** [comment]
Sure, what would you like to pick up?

**Comment by TobiasBK** [comment]
I can finish writing the tests if you'd like

**Comment by 0xAlcibiades** [comment]
> 

Feel free to submit a pull request
